Repository MicrosoftDocs/architecture-center.zh-tw, pull requests merged in 2018-06, with the labels that each got.

#8 Update scalable-web-app.md
  docs/reference-architectures/app-service-web-app/scalable-web-app.md
Labels: Accepted, Linguistic Suggestion

#5 Update prat of pillars.md
  docs/guide/pillars.md
Labels: Accepted, Linguistic Suggestion

#6 Update naming-conventions.md
  docs/best-practices/naming-conventions.md
Labels: Accepted, Linguistic Suggestion, Source Issue

#7 Update basic-web-app.md
  docs/reference-architectures/app-service-web-app/basic-web-app.md
Labels: In Progress, Linguistic Suggestion

#9 Change zh-tw translate
  docs/reference-architectures/app-service-web-app/basic-web-app.md
Labels: Accepted, Linguistic Suggestion

#12 update pillars.md
  docs/guide/pillars.md
Labels: Accepted, Linguistic Suggestion

#14 Revise "Data Pipeline" Section
  docs/reference-architectures/data/enterprise-bi-sqldw.md
Labels: Accepted, Linguistic Suggestion
